### ISSUE TITLE
lunch lineage_lilac-userdebug: Don't have a product spec for: 'lineage_lilac'

### ISSUE THREAD

**Issue by foresto** [Flamefire/lineageos_lilac#1]
I've run into a problem with the v17.1-20230513 build. Any idea what's wrong here?

    $ lunch lineage_lilac-userdebug
    16:07:07 Build sandboxing disabled due to nsjail error.
    frameworks/native/build/phone-xhdpi-4096-dalvik-heap.mk:19: error: _nic.PRODUCTS.[[device/sony/lilac/lineage_lilac.mk]]: "vendor/sony/lilac/lilac-vendor.mk" does not exist.
    16:07:08 dumpvars failed with: exit status 1
    Device lilac not found. Attempting to retrieve device repository from LineageOS Github (http://github.com/LineageOS).
    Repository for lilac not found in the LineageOS Github repository list. If this is in error, you may need to manually add it to your local_manifests/roomservice.xml.
    16:07:08 Build sandboxing disabled due to nsjail error.
    frameworks/native/build/phone-xhdpi-4096-dalvik-heap.mk:19: error: _nic.PRODUCTS.[[device/sony/lilac/lineage_lilac.mk]]: "vendor/sony/lilac/lilac-vendor.mk" does not exist.
    16:07:09 dumpvars failed with: exit status 1
    16:07:09 Build sandboxing disabled due to nsjail error.
    frameworks/native/build/phone-xhdpi-4096-dalvik-heap.mk:19: error: _nic.PRODUCTS.[[device/sony/lilac/lineage_lilac.mk]]: "vendor/sony/lilac/lilac-vendor.mk" does not exist.
    16:07:09 dumpvars failed with: exit status 1

    ** Don't have a product spec for: 'lineage_lilac'
    ** Do you have the right repo manifest?

(The "sandboxing disabled" message is normal, but I don't recall ever seeing "device lilac not found" before.)

**Comment by foresto** [comment]
The `device/sony/lilac` and `vendor/sony/lilac` dirs are populated just as I would expect from the manifest.

I notice that `vendor/sony/lilac` is empty except for the `proprietary` dir, but that doesn't appear to be new since my last successful build. (I think my last build was v17.1-20230331.)

**Comment by Flamefire** [comment]
You forgot to extract the proprietary blobs, i.e. `extract-files.sh`

**Comment by foresto** [comment]
I didn't forget to extract the blobs, as they were still present under `vendor/sony/lilac/proprietary`, but your comment drew my attention to the actual problem:

I didn't realize the blob extraction script is also responsible for the project files in `vendor/sony/lilac` . (I don't remember that being the case back when I started building Android, but it has been a while.) It seems either git or repo removed those files when I reset my project dirs to accept your new merged ASB patches. (The March patches had already been applied, so they conflicted with these new merged ones.)

Anyway, thanks for the pointer. I'll try another build soon, and maybe write a script to clean project dirs without killing those files.
