### ISSUE TITLE
"github.com[0: 140.82.112.3]: errno=Connection timed out"

### ISSUE THREAD

**Issue by the-r3dacted** [Flamefire/lineageos_lilac#2]
When running "repo init -u git://github.com/LineageOS/android.git -b lineage-17.1", I get this error.

> repo: reusing existing repo client checkout in /home/administrator/lineageos
>      
> manifests:
> fatal: unable to connect to github.com:
> github.com[0: 140.82.112.3]: errno=Connection timed out
> 
> manifests: sleeping 4.0 seconds before retrying
> 
> manifests:
> fatal: unable to connect to github.com:
> github.com[0: 140.82.114.3]: errno=Connection timed out
> 
> fatal: cannot obtain manifest git://github.com/LineageOS/android.git

**Comment by Flamefire** [comment]
That is a github issue which should resolve itself, nothing related in particular to this repo(s)

**Comment by the-r3dacted** [comment]
> That is a github issue which should resolve itself, nothing related in particular to this repo(s)

The only reason I want to compile is to add this to the ROM, but if you can do that, it would help me out.
https://github.com/kumikooumae/android_vendor_extra
