### ISSUE TITLE
Files don't exist running lunch lineage_lilac-userdebug command

### ISSUE THREAD

**Issue by the-r3dacted** [Flamefire/lineageos_lilac#3]
I get this error trying to run lunch lineage_lilac-userdebug

`administrator@Android-VM:~/lineageos$ lunch lineage_lilac-userdebug
frameworks/native/build/phone-xhdpi-4096-dalvik-heap.mk:19: error: _nic.PRODUCTS.[[device/sony/lilac/lineage_lilac.mk]]: "vendor/sony/lilac/lilac-vendor.mk" does not exist.
19:02:18 dumpvars failed with: exit status 1
Device lilac not found. Attempting to retrieve device repository from LineageOS Github (http://github.com/LineageOS).
Repository for lilac not found in the LineageOS Github repository list. If this is in error, you may need to manually add it to your local_manifests/roomservice.xml.
frameworks/native/build/phone-xhdpi-4096-dalvik-heap.mk:19: error: _nic.PRODUCTS.[[device/sony/lilac/lineage_lilac.mk]]: "vendor/sony/lilac/lilac-vendor.mk" does not exist.
19:02:19 dumpvars failed with: exit status 1
frameworks/native/build/phone-xhdpi-4096-dalvik-heap.mk:19: error: _nic.PRODUCTS.[[device/sony/lilac/lineage_lilac.mk]]: "vendor/sony/lilac/lilac-vendor.mk" does not exist.
19:02:19 dumpvars failed with: exit status 1
 
** Don't have a product spec for: 'lineage_lilac'
** Do you have the right repo manifest?`

**Comment by Flamefire** [comment]
Same as #1
See https://github.com/Flamefire/lineageos_lilac/issues/1#issuecomment-1550894215

> You forgot to extract the proprietary blobs, i.e. `extract-files.sh`

**Comment by the-r3dacted** [comment]
No, I extracted them, I got them from G8441_Customized US_47.2.A.11.228-R7C, extracted them with unsin, mounted the ext4's, extracted the kernel img, copied the ext4's, and ran that command.

What I want is to build this with SystemUIWithLegacyRecents, it'll probably just be easier for you to add it to your build and make one. It won't work as is, you'll need to add revision="refs/heads/master" to the project in the manifests file.
https://github.com/kumikooumae/android_vendor_extra

**Comment by the-r3dacted** [comment]
I tried this again, recorded a video, and I got past it? However I ran into another error.

**Comment by the-r3dacted** [comment]
Oh, I need to use non-US firmware, which I don't have, lemme download that.

**Comment by the-r3dacted** [comment]
No it just doesn't copy a bunch of files from my extracted shit. I have to do it manually.
