### ISSUE TITLE
Impossible to build without already being set up

### ISSUE THREAD

**Issue by the-r3dacted** [Flamefire/lineageos_lilac#4]
This is impossible to build. Here are the biggest problems with this repo.

repo init -u git://github.com/LineageOS/android.git -b lineage-17.1
git:// is not usable anymore, https:// must be used instead.

extract-files.sh misses many files, or the compiling process expects files in wrong places.

Try compiling this with a fresh Ubuntu install. If you can do it and find I'm doing something wrong, I'll accept that. However I see no way that I'm doing anything wrong unless your instructions are bad or missing a step.

**Comment by Flamefire** [comment]
>  git:// is not usable anymore, https:// must be used instead.

Yep, that became outdated, fixed.

> extract-files.sh misses many files, or the compiling process expects files in wrong places.

I regularly compile with completely clean git repos (i.e. `git checkout . && git clean -fxd`) and into newly created output folders.
So it must be something on your end. What I often ran into was aborting `extract-files.sh` which ends up with deleted files in the vendor repo. However this can be fixed by `git checkout .` in that repo.

**Comment by the-r3dacted** [comment]
What firmware do you use as a base? It could be firmware as that is the only thing that I don't think is accounted for.

**Comment by Flamefire** [comment]
47.2.A.11.228 (variant GLOBAL-LTE4A, but I don't think that matters) as documented. If you post the issue or the supposedly missing files I could help more.

**Comment by the-r3dacted** [comment]
I don't see GLOBAL-LTE4A in XperiFirm. I guess I should ask what market or operator the firmware is? Going to try CE1.

**Comment by the-r3dacted** [comment]
I was building for a different device and discovered this website.
https://luk1337.github.io/muppets/
It basically gives you a .xml file that adds the proprietary blobs for a device when you repo sync. (Doesn't have XZ1C unfortunately) Why not set up something similar to make building easier/doable?

**Comment by the-r3dacted** [comment]
> 47.2.A.11.228 (variant GLOBAL-LTE4A, but I don't think that matters) as documented. If you post the issue or the supposedly missing files I could help more.

So I decided to try Customized DE now and I was able to get a successful build that boots and works. (Maybe having muppets for XZ2C on same machine helped idk.) However there is a massive issue, I can't seem to get MicroG working. If I compile your build with MicroG, it does not boot if I format data. If I add MicroG using an installer the ROM gets all buggy and certain parts of settings like Bluetooth or the Battery Manager freeze the settings app. I have no idea what I'm doing wrong. I followed the instructions in this repo. I also tried compiling XZ2C with MicroG and I have the same issue there too, so it has to be something I'm doing wrong, but I have no idea what.

For building with MicroG, I spotted the xml in manifests, and according to the repo I just need to "export WITH_GMS=true", which is what I did. Is there anything else I need to do for MicroG?

**Comment by Flamefire** [comment]
Just a couple last hints:
- When switching between MicroG and non-MicroG builds I clear the out-directory or at least issue a `mka installclean` first
- If you have OpenGapps (or others) installed before switching to MicroG you'll need to wipe /system before flashing a MicroG ROM or OpenGapps will still be there
- There are a few more things to do for building MicroG, all described in their repo, their docker files and build scripts. Checkout my build script I derived of theirs: https://github.com/Flamefire/lineageos_lilac/blob/main/build_scripts/buildMicroG.sh

I hope that helps as I unfortunately can't afford more time on this as I already spent way too much time on LOS getting my own builds to work and updated over all those versions.

**Comment by the-r3dacted** [comment]
> I hope that helps as I unfortunately can't afford more time on this as I already spent way too much time on LOS getting my own builds to work and updated over all those versions.

I'm a bit dumb. I think I want to restart, XZ1C only, using your build scripts. How exactly would I go about doing that? What paths do I need to use? I tried looking through them to change them or use them, but I'm not really sure what like $PWD and all means.

**Comment by the-r3dacted** [comment]
So I got it to compile and work by applying the signature spoofing patch mentioned only in the docker repo. It seems to be working fine now. However there is a weird issue. Not sure if it's my display dying, something missing with blobs, or something else I missed, but touch input feels a bit off. It seems to miss inputs every so often. I have to press harder than I did before or multiple times. I'll revert to stock and see how it feels there.

Edit: It seems to clear up after a bit. Wonder if it's just some lag or whatever as Android is configuring itself.

**Comment by the-r3dacted** [comment]
> I hope that helps as I unfortunately can't afford more time on this as I already spent way too much time on LOS getting my own builds to work and updated over all those versions.

@Flamefire I hope it's not too much to ask, but do you know how exactly the XZ1C has Sony Camera, Xperia Parts, and such? I would like to try porting them to the XZ2C. I would've tried figuring this out on my own, but I encountered a bit of a problem, my XZ1C is dead. It's not related to ROMs, the display just died. There was no visible physical damage to the display or ribbon cable, it just stopped turning on. I would like to get these on the XZ2C before I try maining it. For now I will be using the XA2 with 15.1 if I can get it to compile.

**Comment by the-r3dacted** [comment]
I did it for https://github.com/Eclipse-Community/build-lineage so closing.
